[WBCAMS-184] fix job seeker report
bcgov/workbc-jb pull request #124
Opened 2024-04-02 19:31 UTC by jonathan-longe

Remove stored procedure call.  Will run separately on a schedule instead.

## Deployment instructions:
 set up schedule to run `usp_GenerateJobSeekerStats` on the 7th, 14th, 21st, 28th and the very last day of the month.

2024-04-02 19:35 UTC, infojunkie requested changes
It's not clear to me how the date is expected to be parameterized on the command line

2024-04-02 20:12 UTC, jonathan-longe commented
> It's not clear to me how the date is expected to be parameterized on the command line

Yes, good question. I added a comment in Jira to get Vick's feedback on how he'd like us to do this. Using Powershell, we can run the `sqlcmd` like this:  `sqlcmd -S <removed>\SQLEXPRESS01 -d '<removed>' -q "EXEC dbo.usp_GenerateJobSeekerStats '$([datetime]::now.tostring("yyyy-MM-dd"))'"`.  The alternative approach is to modify the stored procedure so that in the event that the date parameter is not provided it defaults to the current date.  My preference is to be explicit and require the date be passed in.  Are you okay with this approach?

2024-04-02 20:59 UTC, infojunkie approved these changes
Looks great, thanks!

2024-04-02 21:13 UTC, jonathan-longe commented
@infojunkie should I postpone merging this PR until we're sure that IMB can run the stored procedure as proposed?

2024-04-02 21:17 UTC, infojunkie commented
Yes, let's get confirmation from IMB first.

2024-05-14 17:45 UTC, jonathan-longe commented
@infojunkie any objection if I merge this PR now that Vik has confirmed he can run the stored procedure as proposed?

2024-05-14 18:32 UTC, infojunkie commented
No objection - go ahead!

2024-05-14 18:44 UTC, merged